// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCllrItXiycoK9a9zKVGnFLvFm1rs4msiw',
    appId: '1:502339643701:web:318282a7186bc01d84c47c',
    messagingSenderId: '502339643701',
    projectId: 'surveywebapptest',
    authDomain: 'surveywebapptest.firebaseapp.com',
    storageBucket: 'surveywebapptest.appspot.com',
    measurementId: 'G-BJYSSN4QX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApg0tr2hnKtZ87eWVZhEbgs_ACTAEYciw',
    appId: '1:502339643701:android:c0ca0fe55b3ed75a84c47c',
    messagingSenderId: '502339643701',
    projectId: 'surveywebapptest',
    storageBucket: 'surveywebapptest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpjyQVQuDQJt42DwJtkuxipZvu0mF2MRA',
    appId: '1:502339643701:ios:0f741b5bcf16e78a84c47c',
    messagingSenderId: '502339643701',
    projectId: 'surveywebapptest',
    storageBucket: 'surveywebapptest.appspot.com',
    iosClientId: '502339643701-bqtimeuv02n23ramv2am35i761kg1g98.apps.googleusercontent.com',
    iosBundleId: 'com.example.databaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpjyQVQuDQJt42DwJtkuxipZvu0mF2MRA',
    appId: '1:502339643701:ios:0f741b5bcf16e78a84c47c',
    messagingSenderId: '502339643701',
    projectId: 'surveywebapptest',
    storageBucket: 'surveywebapptest.appspot.com',
    iosClientId: '502339643701-bqtimeuv02n23ramv2am35i761kg1g98.apps.googleusercontent.com',
    iosBundleId: 'com.example.databaseTest',
  );
}
